Added FanOut/FanIn pattern
miqdigital/java-design-patterns pull request #1
Opened 2021-06-14 18:17 UTC by karthikbhat13

FanOut/FanIn Pattern

- The pattern refers to executing multiple instances of the activity function on multiple chunks in parallel
- Resolved #1627

Pull request description

- Added code that implements the design pattern and test cases

2021-06-15 07:13 UTC, tan31989 requested changes

2021-06-15 07:13 UTC, ntantri commented on fanout-fanin/etc/fanout-fanin.urm.puml
> +@enduml
Are there no relationships among "Associations" that can be depicted?

2021-06-15 10:31 UTC, karthikbhat13 commented on fanout-fanin/etc/fanout-fanin.urm.puml
> +@enduml
I am kinda unaware of how it works. If one class is calling one more class as callback, is that an association?
I think it is right.

2021-06-15 15:34 UTC, karthikbhat13 commented on fanout-fanin/etc/fanout-fanin.urm.puml
> +@enduml
I have updated!

2021-06-16 01:31 UTC, tan31989 commented on fanout-fanin/etc/fanout-fanin.urm.puml
> +@enduml
Yes, the association bit is right and I think you have got It updated.

2021-06-16 01:31 UTC, tan31989 approved these changes

2021-06-16 06:04 UTC, merged